# -*- coding: utf-8 -*-
"""Copy of Assignment-2 Fundamentals of Print, Variables, Datatypes, and If-Else.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oECd9SAjuqVjuM4dxDViLES658Tdsgt2

## **Objective:**
understanding of basic Python syntax, including the use of the print() function, variables, different datatypes, and decision-making using if-else statements.

## **Problem 1: Temperature Converter**
Write a Python program that:
1. Takes temperature input from the user in Celsius.
2. Converts the temperature to Fahrenheit using the formula:  
 `Fahrenheit = (Celsius × 9/5) + 32`
3. Prints both the Celsius and Fahrenheit temperatures in a well-formatted way.
4. Use an `if-else` statement to check if the temperature is below freezing (0°C), between 0°C and 30°C, or above 30°C. Print appropriate messages for each case.
5. Temp < 0: The temp is freezing
6. Temp < 30: The temp is moderate
7. Temp > 30: Temp is hot
"""

user_tem_input=int(input("Enter Temmpeture in Celsius"))
conversion_fohrenheit=(user_tem_input*9/5)+32
print("Tempeture in Fahrenheit :" ,conversion_fohrenheit)
print("Tempeture in Celsius :" ,user_tem_input)
if user_tem_input<0:
  print("The temp is freezing")
elif user_tem_input<30:
  print("The temp is moderate")
else:
  print("Temp is hot")

"""## **Problem 2: Simple Calculator**
Write a Python program that:
1. Takes two numbers as input from the user (you may assume the inputs are valid integers or floats).
2. Asks the user which operation they want to perform: addition, subtraction, multiplication, or division.
3. Performs the selected operation and prints the result.
4. Ensure that if the user chooses division, the program checks for division by zero and prints an appropriate message.

"""

Input_1=int(input("Enter First Number :"))
input_2=int(input("Enter second Number :"))
print("Choose from the Operation to perform")
print("1.Addition")
print("2.Subtraction")
print("3.Multiplication")
print("4.Division")
input_operation=int(input("Enter your choice :"))
if input_operation==1:
  print("Addition of two numbers :",Input_1+input_2)
elif input_operation==2:
  print("Subtraction of two numbers :",Input_1-input_2)
elif input_operation==3:
  print("Multiplication of two numbers :",Input_1*input_2)
elif input_operation==4:
  if input_2==0:
    print("Division by zero is not possible")
  else:
         print("Division of two numbers :",Input_1/input_2)

"""## **Problem 3: Even or Odd?**
Write a Python program that:
1. Takes an integer input from the user.
2. Uses an `if-else` statement to determine if the number is even or odd.
3. Print whether the number is even or odd.
"""

user_input_number=int(input("Enter a number :"))
if user_input_number%2==0:
  print("Number is even")
else:
  print("Number is odd")

"""## **Problem 4: Age and Voting Eligibility**
Write a Python program that:
1. Takes the user's age as input.
2. Uses an `if-else` statement to check if the user is eligible to vote (age 18 and above).
3. Prints a message letting the user know whether they are eligible or not.
"""

user_age=int(input("Enter your age :"))
if user_age>=18:
  print("You are eligible to vote")
else:
  print("You are not eligible to vote")

"""## **Problem 5: Grading System**
Write a Python program that:
1. Takes the score (out of 100) as input from the user.
2. Uses `if-else` statements to print the corresponding grade based on the score:
   - 90 and above: A
   - 80-89: B
   - 70-79: C
   - 60-69: D
   - Below 60: F
"""

Total_marks=100
user_score=int(input("Enter your score :"))
if user_score>=90:
  print("Grade A")
elif user_score>=80:
  print("Grade B")
elif user_score>=70:
  print("Grade C")
elif user_score>=60:
  print("Grade D")
else:
  print("Grade F")

